gnuplot -e "outputFile='plots/VTerm_0.eps';\
    xTitle='Board #';\
    yTitleVn='VTerm_n [V]';\
    yTitleVp='VTerm_p [V]';\
    yTitleI='Total current [mA]';\
    plotTitle='HE buffer board VTerm set & current: channel 0';\
    channel=0;\
    yup0=1.06;\
    ydown0=0.90;\
    yup1=0.96;\
    ydown1=0.82;\

     inputFile='data/Raw_Buffer.tsv';" gnuplotScripts/VTerm_script.gpi
gnuplot -e "outputFile='plots/VTerm_1.eps';\
    xTitle='Board #';\
    yTitleVn='VTerm_n [V]';\
    yTitleVp='VTerm_p [V]';\
    yTitleI='Total current [mA]';\
    plotTitle='HE buffer board VTerm set current: channel 1';\
    channel=1;\
    yup0=1.06;\
    ydown0=0.90;\
    yup1=0.96;\
    ydown1=0.82;\

     inputFile='data/Raw_Buffer.tsv';" gnuplotScripts/VTerm_script.gpi
gnuplot -e "outputFile='plots/VTerm_2.eps';\
    xTitle='Board #';\
    yTitleVn='VTerm_n [V]';\
    yTitleVp='VTerm_p [V]';\
    yTitleI='Total current [mA]';\
    plotTitle='HE buffer board VTerm set current: channel 2';\
    channel=2;\
    yup0=1.06;\
    ydown0=0.90;\
    yup1=0.96;\
    ydown1=0.82;\

     inputFile='data/Raw_Buffer.tsv';" gnuplotScripts/VTerm_script.gpi
gnuplot -e "outputFile='plots/VTerm_3.eps';\
    xTitle='Board #';\
    yTitleVn='VTerm_n [V]';\
    yTitleVp='VTerm_p [V]';\
    yTitleI='Total current [mA]';\
    plotTitle='HE buffer board VTerm set current: channel 3';\
    channel=3;\
    yup0=1.06;\
    ydown0=0.90;\
    yup1=0.96;\
    ydown1=0.82;\

     inputFile='data/Raw_Buffer.tsv';" gnuplotScripts/VTerm_script.gpi
gnuplot -e "outputFile='plots/VTerm_4.eps';\
    xTitle='Board #';\
    yTitleVn='VTerm_n [V]';\
    yTitleVp='VTerm_p [V]';\
    yTitleI='Total current [mA]';\
    plotTitle='HE buffer board VTerm set current: channel 4';\
    channel=4;\
    yup0=1.06;\
    ydown0=0.90;\
    yup1=0.96;\
    ydown1=0.82;\

     inputFile='data/Raw_Buffer.tsv';" gnuplotScripts/VTerm_script.gpi
gnuplot -e "outputFile='plots/VTerm_5.eps';\
    xTitle='Board #';\
    yTitleVn='VTerm_n [V]';\
    yTitleVp='VTerm_p [V]';\
    yTitleI='Total current [mA]';\
    plotTitle='HE buffer board VTerm set current: channel 5';\
    channel=5;\
    yup0=1.06;\
    ydown0=0.90;\
    yup1=0.96;\
    ydown1=0.82;\

     inputFile='data/Raw_Buffer.tsv';" gnuplotScripts/VTerm_script.gpi
gnuplot -e "outputFile='plots/VTerm_6.eps';\
    xTitle='Board #';\
    yTitleVn='VTerm_n [V]';\
    yTitleVp='VTerm_p [V]';\
    yTitleI='Total current [mA]';\
    plotTitle='HE buffer board VTerm set current: channel 6';\
    channel=6;\
    yup0=1.06;\
    ydown0=0.90;\
    yup1=0.96;\
    ydown1=0.82;\

     inputFile='data/Raw_Buffer.tsv';" gnuplotScripts/VTerm_script.gpi
