gnuplot -e "outputFile='plots/VOut_0.eps';\
    xTitleI='Board #';\
    yTitleI='VOut_n [V]';\
    xTitleV='Board #';\
    yTitleV='VOut_p [V]';\
    plotTitle='HE buffer board diff out: channel 0';\
    channel=0;\
    yup0=1.06;\
    ydown0=0.90;\
    yup1=0.96;\
    ydown1=0.82;\

     inputFile='data/Raw_Buffer.tsv';" gnuplotScripts/VOut_script.gpi
gnuplot -e "outputFile='plots/VOut_1.eps';\
    xTitleI='Board #';\
    yTitleI='VOut_n [V]';\
    xTitleV='Board #';\
    yTitleV='VOut_p [V]';\
    plotTitle='HE buffer board diff out: channel 1';\
    channel=1;\
    yup0=1.06;\
    ydown0=0.90;\
    yup1=0.96;\
    ydown1=0.82;\

     inputFile='data/Raw_Buffer.tsv';" gnuplotScripts/VOut_script.gpi
gnuplot -e "outputFile='plots/VOut_2.eps';\
    xTitleI='Board #';\
    yTitleI='VOut_n [V]';\
    xTitleV='Board #';\
    yTitleV='VOut_p [V]';\
    plotTitle='HE buffer board diff out: channel 2';\
    channel=2;\
    yup0=1.06;\
    ydown0=0.90;\
    yup1=0.96;\
    ydown1=0.82;\

     inputFile='data/Raw_Buffer.tsv';" gnuplotScripts/VOut_script.gpi
gnuplot -e "outputFile='plots/VOut_3.eps';\
    xTitleI='Board #';\
    yTitleI='VOut_n [V]';\
    xTitleV='Board #';\
    yTitleV='VOut_p [V]';\
    plotTitle='HE buffer board diff out: channel 3';\
    channel=3;\
    yup0=1.06;\
    ydown0=0.90;\
    yup1=0.96;\
    ydown1=0.82;\

     inputFile='data/Raw_Buffer.tsv';" gnuplotScripts/VOut_script.gpi
gnuplot -e "outputFile='plots/VOut_4.eps';\
    xTitleI='Board #';\
    yTitleI='VOut_n [V]';\
    xTitleV='Board #';\
    yTitleV='VOut_p [V]';\
    plotTitle='HE buffer board diff out: channel 4';\
    channel=4;\
    yup0=1.06;\
    ydown0=0.90;\
    yup1=0.96;\
    ydown1=0.82;\

     inputFile='data/Raw_Buffer.tsv';" gnuplotScripts/VOut_script.gpi
gnuplot -e "outputFile='plots/VOut_5.eps';\
    xTitleI='Board #';\
    yTitleI='VOut_n [V]';\
    xTitleV='Board #';\
    yTitleV='VOut_p [V]';\
    plotTitle='HE buffer board diff out: channel 5';\
    channel=5;\
    yup0=1.06;\
    ydown0=0.90;\
    yup1=0.96;\
    ydown1=0.82;\

     inputFile='data/Raw_Buffer.tsv';" gnuplotScripts/VOut_script.gpi
gnuplot -e "outputFile='plots/VOut_6.eps';\
    xTitleI='Board #';\
    yTitleI='VOut_n [V]';\
    xTitleV='Board #';\
    yTitleV='VOut_p [V]';\
    plotTitle='HE buffer board diff out: channel 6';\
    channel=6;\
    yup0=1.06;\
    ydown0=0.90;\
    yup1=0.96;\
    ydown1=0.82;\

     inputFile='data/Raw_Buffer.tsv';" gnuplotScripts/VOut_script.gpi
